### ISSUE TITLE
Trivy javadb poor performance in 0.37.2

### ISSUE THREAD

**Issue by dmivankov** [aquasecurity/trivy-java-db#12]
In 0.37.1 there was a reported issue about slow scan for java vulnerabilities https://github.com/aquasecurity/trivy-java-db/issues/8

The provided workaround of manually creating sqlite indexes was helping to bring good scan times back.
In 0.37.2 and with newer versions of java-db the issue still exists but the workaround of creating indexes with
```
sqlite3 db/java-db/trivy-java.db << EOF
CREATE INDEX sha1 ON indices (sha1);
CREATE INDEX artifact_id_group_id ON indices (artifact_id, group_id);
CREATE INDEX artifact_id_archive_type ON indices (artifact_id, archive_type);
EOF
```
doesn't apply as it fails with
```
Parse error near line 2: no such column: group_id
  DEX artifact_id_group_id ON indices (artifact_id, group_id);
                                      error here ---^
```

Variation of workaround script like this
```
sqlite3 db/java-db/trivy-java.db << EOF
CREATE INDEX sha1 ON indices (sha1);
CREATE INDEX artifact_id ON indices (artifact_id);
CREATE INDEX artifact_id_archive_type ON indices (artifact_id, archive_type);
EOT
```
can create indexes but scans are still slow and consuming a lot of cpu (probably 0.37.2 changed not only the schema but also the queries in a way that doesn't benefit from indexes above anymore)

**Comment by DmitriyLewen** [comment]
Hello @dmivankov 

New DB schema already has indexes for  `sha1` and `artifact_id + group_id`.
We tested performance after changes and new DB has very high speed.

Can you share some image/jar of your issue for investigation?

**Comment by dmivankov** [comment]
Will try to profile it, one image has 355 jar files (external libraries), trivy process consumes 500% cpu (so runs 5 threads), after 4 minutes it is still running, so slow.
`trivy` binary doesn't have debug symbols so can provide hot stacktraces
With debug output enabled it slowly shows messages like these
```
2023-02-14T16:49:27.106Z	DEBUG	Parsing Java artifacts...	{"file": "....../com/github/spotbugs/spotbugs-annotations/4.2.0/processed_spotbugs-annotations-4.2.0.jar"}
2023-02-14T16:49:27.107Z	DEBUG	No such POM in the central repositories	{"file": "processed_spotbugs-annotations-4.2.0.jar"}
```
at ballpark rate of 1 jar per second

**Comment by dmivankov** [comment]
This helps to bring scan time to ~3sec
```
sqlite3 trivy-java.db <<EOT
CREATE INDEX artifact_id_group_id ON artifacts (artifact_id, group_id);
CREATE INDEX artifact_id ON indices (artifact_id);
EOT
```
both indices are required to make it fast

**Comment by eanmclaughlin** [comment]
Can confirm with 0.37.3 as well. MacOS 64 bit (not ARM).

**Comment by DmitriyLewen** [comment]
Hello @dmivankov
1st index (`CREATE INDEX artifact_id_group_id ON artifacts (artifact_id, group_id);`) already exist - https://github.com/aquasecurity/trivy-java-db/blob/7cddb14067284564be63e70b2d2097202f611402/pkg/db/db.go#L66

Hello @eanmclaughlin 
I tested this idea with another index(`CREATE INDEX artifact_id ON indices (artifact_id);`) - but i didn't see any speed increase.

Can you send some test image and we will investigate it.

**Comment by dmivankov** [comment]
Yes, index above exists
```
$ sqlite3 trivy-java.db <<EOT
. indexes
EOT

artifacts_idx     indices_sha1_idx
```
but it has flipped order and probably can't be used for lookups by `artifact_id` key prefix
https://github.com/aquasecurity/trivy-java-db/blob/main/pkg/db/db.go#L62
and `artifact_id` isn't a primary key so doesn't have implicit index

Can also confirm that flipped order is still slow
```
CREATE INDEX group_id_artifact_id ON artifacts (group_id, artifact_id);
CREATE INDEX artifact_id ON indices (artifact_id);
```

It could be possible to use sqlite debugging https://www.sqlite.org/debugging.html to get more info on query plans etc, but don't currently have enough spare time to do it myself. Also preparing a public image also needs time. But general setup is just offline scan of image with 300+ jars of maven repository libraries (maybe even using 300 copies of same jar can be used to reproduce the issue, didn't test).

**Comment by tillkuhn** [comment]
@dmivankov thanks for the analysis, we made similar experiences. most scans are back to OK times with the most recent trivy update to 0.37.2, but especially those with a lot of jar files still take quite long, some of which even run into the 5m default timeout. @DmitriyLewen I also can't share our internal images, but the official gradle image on dockerhub seems to be a good candidate, as the latest version contains at least 239 jars.  `trivy image  --debug  gradle:latest` takes at least 2 minutes on a small EC2 machine without previous caching (db download not included). I have no reference values for older trivy versions, but I can say with confidence that in our environment the number of "long scans" for Java images is still higher than it used to be before the local-java-db was introduced, and the images themselves  have not changed very much. Thanks for your help!

```
2023-02-15T19:42:45.074Z	DEBUG	Parsing Java artifacts...	{"file": "opt/gradle/lib/plugins/plexus-utils-3.3.0.jar"}
2023-02-15T19:42:45.077Z	DEBUG	Parsing Java artifacts...	{"file": "opt/gradle/lib/plugins/snakeyaml-1.32.jar"}
2023-02-15T19:42:45.095Z	DEBUG	Parsing Java artifacts...	{"file": "opt/gradle/lib/qdox-1.12.1.jar"}
2023-02-15T19:42:45.098Z	DEBUG	Parsing Java artifacts...	{"file": "opt/gradle/lib/slf4j-api-1.7.30.jar"}
2023-02-15T19:42:45.098Z	DEBUG	Parsing Java artifacts...	{"file": "opt/gradle/lib/plugins/testng-6.3.1.jar"}
2023-02-15T19:42:45.118Z	DEBUG	Parsing Java artifacts...	{"file": "opt/gradle/lib/trove4j-1.0.20200330.jar"}
2023-02-15T19:42:45.120Z	DEBUG	Parsing Java artifacts...	{"file": "opt/gradle/lib/tomlj-1.0.0.jar"}
2023-02-15T19:42:45.122Z	DEBUG	Parsing Java artifacts...	{"file": "opt/gradle/lib/xml-apis-1.4.01.jar"}
(...)
```

**Comment by dheeg** [comment]
This performance issue is related to https://github.com/aquasecurity/trivy/issues/3608
After creating the two additional indexes mentioned by @dmivankov the newrelic image can be scanned in light speed.

The indexes or queries need to be adjusted.
