### ISSUE TITLE
Unable to download trivy-java-db using trivy

### ISSUE THREAD

**Issue by harishnerella** [aquasecurity/trivy-java-db#17]
I am trying to download the trivy-java-db using trivy but everytime I am getting unauthorized error eventhough I have a valid credentials. Using the same credentials I was able to download the trivy-db but not trivy-java-db.

Is there and change in authorization mechanism ?

**Comment by knqyf263** [comment]
No, they are completely the same.

**Comment by harishnerella** [comment]
Thank you for the response.
I am using the below snippet to download the db. The same snippet (with db config parameters) is able to download the vulnerability db but getting unauthorized error when downloading java db.

withCredentials([usernamePassword(credentialsId: env.TRIVY_CREDENTIALS_ID, usernameVariable: 'TRIVY_USER', passwordVariable: 'TRIVY_PASS')]){
    sh '''
        trivy_dir/trivy image --reset
        TRIVY_TEMP_DIR=$(mktemp -d)
        trivy_dir/trivy --username $TRIVY_USER --password $TRIVY_PASS  --java-db-repository container-proxy-lab.services.eden/aquasecurity/trivy-java-db --cache-dir $TRIVY_TEMP_DIR image --download-java-db-only
        tar -cf ./javadb.tar.gz -C $TRIVY_TEMP_DIR/java-db metadata.json trivy-java.db
        rm -rf $TRIVY_TEMP_DIR
      '''
  }

I even tried to use the token instead of username but no use. Am I missing anything?
