### ISSUE TITLE
Add latest tag

### ISSUE THREAD

**Issue by exaws** [aquasecurity/trivy-java-db#18]
Hi,

To keep aligned with a common practice and trivy-db, it would be good to have a latest tag pointing to the latest oci image.

Thanks,
N.

**Comment by knqyf263** [comment]
We don't think the latest is needed. A different version means breaking change. The latest tag should not be used.

**Comment by exaws** [comment]
I cannot see how this is a breaking change as the tag 1 stays as is and only the latest tag is added, f.e. see: https://github.com/aquasecurity/trivy-db/pkgs/container/trivy-db

I will not argue with you, close the PR if you stick with won't do.
