### ISSUE TITLE
Trivy performance bad because of missing indexes

### ISSUE THREAD

**Issue by dheeg** [aquasecurity/trivy-java-db#8]
Hi,

thanks for the Trivy 0.37.1 release today which is a step into the right direction.

I played around a bit and quickly discovered that the performance is way worse compared to the API version before (if the API is currently not running into 504 errors).

After digging into it, I think this is down to the fact that the Java DB comes without any index.

I did run a few tests, always with a fresh Trivy cache folder and got insane performance improvements.

# Run 1 with original database took 2,5 minutes
```
rm -rf db
trivy --cache-dir ./db image --download-db-only
trivy --cache-dir ./db image --download-java-db-only

trivy --debug --cache-dir ./db image --offline-scan --scanners vuln --skip-java-db-update --skip-db-update --format json --output orig.json flowable/all-in-one:latest
```

The indexes are guesses from looking into https://github.com/aquasecurity/trivy-java-db/blob/main/pkg/db/db.go#L63

# Run 2 with changed database took 20 seconds only
```
rm -rf db
trivy --cache-dir ./db image --download-db-only
trivy --cache-dir ./db image --download-java-db-only

sqlite3 db/java-db/trivy-java.db << EOF
CREATE INDEX sha1 ON indices (sha1);
CREATE INDEX artifact_id_group_id ON indices (artifact_id, group_id);
CREATE INDEX artifact_id_archive_type ON indices (artifact_id, archive_type);
EOF

trivy --debug --cache-dir ./db image --offline-scan --scanners vuln --skip-java-db-update --skip-db-update --format json --output ng.json flowable/all-in-one:latest
```

For some of our private images the improvement is even better, since the test with the original database takes 7 minutes. I didn't discover any change the json output.

It would great if you could look into this.

**Comment by knqyf263** [comment]
Thanks. We'll take a look.

**Comment by gpanagiotidis** [comment]
I am also impacted by this. The performance reduction is indeed introduced with v0.37.1.

**Comment by exiett** [comment]
What worked on our environment was to rollback Trivy to 0.36 and applying --offline-scan option to not issue API calls to Maven, as it seems to be unstable still. Monitoring this issue for further improvements on trivy-java-db.

**Comment by knqyf263** [comment]
We're working on this issue, but found out creating indexes increases the database size a lot (more than double). We're looking for ways to keep the size small.

**Comment by orisano** [comment]
My Experiments:
```
no_index;
base:  760M
gzip:  342M
zstd6: 273M
zstd8: 269M

sha1_blob;
base:  609M
gzip:  300M
zstd6: 237M
zstd8: 234M

with_index;
base:  1.4G
gzip:  583M
zstd6: 493M
zstd8: 489M

sha1_blob + with_index;
base:  1.2G
gzip:  515M 
zstd6: 434M
zstd8: 424M

sha1_blob + separate_artifacts_table + with_index;
base:  676M
gzip:  442M
zstd6: 416M
zstd8: 403M
```

**Comment by cpach** [comment]
Just a thought:

How long does it take to create the index, approximately? (Given ”reasonable” CPU/memory resources – whatever ”reasonable” might mean in this context…)

If it doesn’t take an extreme amount of time, could it perhaps then be an alternative to have Trivy create the index locally, _after_ downloading the database?

**Comment by knqyf263** [comment]
@cpach Thanks for sharing your idea. I was thinking about the same idea, but @orisano found out the better way. We're testing it now.

**Comment by tillkuhn** [comment]
@knqyf263 Thanks for working on this, is there already an ETA for the release? Not sure if this is also related to https://github.com/aquasecurity/trivy-java-db/pull/11 (which hasn't been assigned yet). In our environments, we're mostly dealing with java images, and the performance impact on the scan duration is really significant. According to our stats, we used to have max 3 scans per day that took more than 30s, since the upgrade from 0.36 to 0.37.1 we're facing at least 50 per day, and some of the even run into the default timeout of 5m. Thanks!

**Comment by knqyf263** [comment]
We cut v0.37.2 and it should improve the performance. Please let us know if you still see the same issue with v0.37.2.
https://github.com/aquasecurity/trivy/releases/tag/v0.37.2

Thanks for your patience.

**Comment by dmivankov** [comment]
Yes, 0.37.2 is also very very slow and cpu-hungry.
And workaround also doesn't work anymore
```
sqlite3 db/java-db/trivy-java.db << EOF
CREATE INDEX sha1 ON indices (sha1);
CREATE INDEX artifact_id_group_id ON indices (artifact_id, group_id);
CREATE INDEX artifact_id_archive_type ON indices (artifact_id, archive_type);
EOF

Parse error near line 2: no such column: group_id
  DEX artifact_id_group_id ON indices (artifact_id, group_id);
                                      error here ---^
```

**Comment by dmivankov** [comment]
Using
```console
sqlite3 db/java-db/trivy-java.db << EOF
CREATE INDEX sha1 ON indices (sha1);
CREATE INDEX artifact_id ON indices (artifact_id);
CREATE INDEX artifact_id_archive_type ON indices (artifact_id, archive_type);
EOT
```
doesn't help much

**Comment by dheeg** [comment]
@dmivankov You are replying to a performance issue (and workaround) which was only valid for Trivy 0.37.1
For Trivy version 0.37.2 please open a new issue with your findings.
