### ISSUE TITLE
Strange sha1 values in the DB

### ISSUE THREAD

**Issue by wagde-orca** [aquasecurity/trivy-java-db#9]
There are some strange values as the sha1 in the DB like
./spark-streaming-flume-sink_2.10/1.2.0/spark-streaming-flume-sink_2.10-1.2.0-javadoc.jar: 
./spark-bagel_2.10/1.2.0/spark-bagel_2.10-1.2.0.jar:
...

this is because of maven has some strange format of the sha1 value... for example here
https://repo.maven.apache.org/maven2/org/apache/spark/spark-streaming-flume-sink_2.10/1.2.0/spark-streaming-flume-sink_2.10-1.2.0-javadoc.jar.sha1

I think the relevant code line is
https://github.com/aquasecurity/trivy-java-db/blob/514a759651358abe32e82cfd6a75b53f5ce118bc/pkg/crawler/crawler.go#L270

so I guess this comment is not always true :-)
	// there are xxx.jar.sha1 files with additional data. Sha1 is always 1st word.
	// e.g.https://repo.maven.apache.org/maven2/aspectj/aspectjrt/1.5.2a/aspectjrt-1.5.2a.jar.sha1

**Comment by DmitriyLewen** [comment]
Hello @wagde-orca 
Thanks a lot for information.

I also found this yesterday.

I added changes in this [PR](https://github.com/aquasecurity/trivy-java-db/pull/11/files#diff-526a7142f7b15a72eab215dcfa540f5b6d502951a2f9f3b34dd900013e82c675R275-R292)

**Comment by DmitriyLewen** [comment]
Hello @wagde-orca 
We merged #11.

Can you check this problem and close issue, if there are no errors?

Regards, Dmitriy

**Comment by knqyf263** [comment]
Please feel free to reopen it if you still see the issue.
